### ISSUE TITLE
Module 1, chapter 2 questions

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/exploratory-data-viz#12]
I still think the question below unfairly biases folks towards statistical summaries being not useful:

"True or False: Statistical summaries can be misleading."

Can we soften this to "True or False: Statistical summaries are often useful, but can sometimes be misleading."

I think viz guards agains the "sometimes be misleading". And not all statistical summaries are useless, so I worry about making this point.

**Comment by joelostblom** [comment]
I rephrased this question to be softer in the latest updated to the PR.

**Comment by joelostblom** [comment]
Done
