### ISSUE TITLE
Module 1 general comment

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/exploratory-data-viz#13]
I think given that we do not have a stat course in this set our courses, here we need to spend some time doing a bit of stats, or justification of stats. Also some time to fully motivate! Thus, I strongly feel that we need some intro material to module 1 that shows why data viz is important, and another piece showing that summary stats are useful. This is a very new audience to this field, and these two things are huge expert blind spots on our parts.

**Comment by joelostblom** [comment]
This has now been added
