### ISSUE TITLE
Categorize variable types clearly at some point

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/exploratory-data-viz#73]
Use the same names as in Altair, quantitative, ordinal, nominal, temporal.

@hfboyce do you talk about this in the previous courses? Which names do you use?

**Comment by hfboyce** [comment]
Ah yes, we have a section in [Module 2](https://prog-learn.mds.ubc.ca/en/module2) chapter 29.

**Comment by joelostblom** [comment]
Done in m2 now.
